/**
 * 视频
 */
module.exports = {
    videoConfig:{
        videoApi:[
          {
            name:"M3u8",
            url:"https://www.m3u8.tv.cdn.8old.cn/jx2022/index..php",
            delete:""
          },
          {
            name:"测试1",
            url:"https://json.hfyrw.com/mao.go",
            delete:"Mao"
          }
        ],
        videoUrl:[
          {
            name:"M3u8",
            url:"https://jx.m3u8.tv/jiexi/?url="
          },
          {
            name:"parwix",
            url:"https://jx.parwix.com:4433/player/?url="
          },
          {
            name:"iztyy",
            url:"https://jx.iztyy.com/svip/?url="
          },
          {
            name:"M3u8",
            url:"https://jx.iztyy.com/svip/?url="
          },
          {
            name:"忘忧国",
            url:"https://ax.jx.cn/?url="
          }
      ]
      }
}